run:
  timeout: 5m
  tests: false
  skip-dirs:
    - sdk
    - ai-dev

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
  disable:
    - exhaustruct
    - varnamelen
    - nlreturn
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
