ALTER TABLE ai_usage ADD COLUMN model TEXT NOT NULL DEFAULT '';
ALTER TABLE ai_usage ADD COLUMN prompt_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN completion_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN total_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN latency_ms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN cost_micros INTEGER NOT NULL DEFAULT 0;
