package repository

import (
	"context"
	"database/sql"
	"errors"
	"time"
)

type deliveredGovernanceOrigin struct {
	id          string
	originKind  string
	originID    int64
	deliveredAt int64
}

func (s *sqlStore) CleanupDeliveredAuditGovernance(
	ctx context.Context, before time.Time, limit int,
) (int64, error) {
	if before.IsZero() || limit <= 0 || limit > 500 {
		return 0, errors.New("audit governance cleanup arguments are invalid")
	}
	if s.dialect == dialectPostgres {
		return s.cleanupDeliveredGovernancePostgres(ctx, before, limit)
	}
	return s.cleanupDeliveredGovernanceSQLite(ctx, before, limit)
}

// CleanupFailedAuditGovernance prunes terminal-failed rows (failed_at_ns>0)
// older than before — the mirror of CleanupDeliveredAuditGovernance for the
// conflict-terminal state (migration 0042). Rows are selected by failed_at_ns
// so a failed row is never re-claimed or re-posted, only eventually removed.
// Permanent rows retain their rejected-origin tombstone after this cleanup;
// window-terminal rows intentionally do not and may be regenerated by gaps.
func (s *sqlStore) CleanupFailedAuditGovernance(
	ctx context.Context, before time.Time, limit int,
) (int64, error) {
	if before.IsZero() || limit <= 0 || limit > 500 {
		return 0, errors.New("audit governance cleanup arguments are invalid")
	}
	if s.dialect == dialectPostgres {
		return s.cleanupFailedGovernancePostgres(ctx, before, limit)
	}
	return s.cleanupFailedGovernanceSQLite(ctx, before, limit)
}

func (s *sqlStore) cleanupFailedGovernancePostgres(
	ctx context.Context, before time.Time, limit int,
) (int64, error) {
	result, err := s.db.ExecContext(ctx, `DELETE FROM audit_governance_outbox o
WHERE o.failed_at_ns>0 AND o.failed_at_ns <= $1 AND o.id IN (
 SELECT id FROM audit_governance_outbox WHERE failed_at_ns>0
 ORDER BY failed_at_ns,id LIMIT $2)`,
		before.UTC().UnixNano(), limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

func (s *sqlStore) cleanupFailedGovernanceSQLite(
	ctx context.Context, before time.Time, limit int,
) (int64, error) {
	result, err := s.db.ExecContext(ctx, s.rebind(`DELETE FROM audit_governance_outbox
WHERE failed_at_ns>0 AND failed_at_ns <= $1 AND id IN (
 SELECT id FROM audit_governance_outbox WHERE failed_at_ns>0
 ORDER BY failed_at_ns,id LIMIT $2)`),
		before.UTC().UnixNano(), limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

func (s *sqlStore) cleanupDeliveredGovernancePostgres(
	ctx context.Context, before time.Time, limit int,
) (int64, error) {
	result, err := s.db.ExecContext(ctx, `WITH selected AS (
 SELECT id,origin_kind,origin_id,delivered_at_ns FROM audit_governance_outbox
 WHERE delivered_at_ns>0 AND delivered_at_ns <= $1
 ORDER BY delivered_at_ns,id LIMIT $2 FOR UPDATE SKIP LOCKED
), marked AS (
 INSERT INTO audit_governance_delivered_origins (origin_kind,origin_id,delivered_at_ns)
 SELECT origin_kind,origin_id,delivered_at_ns FROM selected
 ON CONFLICT (origin_kind,origin_id) DO NOTHING
)
DELETE FROM audit_governance_outbox o USING selected s WHERE o.id=s.id`,
		before.UTC().UnixNano(), limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

func (s *sqlStore) cleanupDeliveredGovernanceSQLite(
	ctx context.Context, before time.Time, limit int,
) (int64, error) {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return 0, err
	}
	defer func() { _ = tx.Rollback() }()
	origins, err := s.selectDeliveredGovernance(ctx, tx, before, limit)
	if err != nil {
		return 0, err
	}
	for _, origin := range origins {
		if err := s.cleanupDeliveredGovernanceOrigin(ctx, tx, origin, before); err != nil {
			return 0, err
		}
	}
	return int64(len(origins)), tx.Commit()
}

func (s *sqlStore) selectDeliveredGovernance(
	ctx context.Context, tx *sql.Tx, before time.Time, limit int,
) ([]deliveredGovernanceOrigin, error) {
	rows, err := tx.QueryContext(ctx, s.rebind(`SELECT id,origin_kind,origin_id,delivered_at_ns
FROM audit_governance_outbox WHERE delivered_at_ns>0 AND delivered_at_ns <= $1
ORDER BY delivered_at_ns,id LIMIT $2`), before.UTC().UnixNano(), limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var origins []deliveredGovernanceOrigin
	for rows.Next() {
		var origin deliveredGovernanceOrigin
		if err := rows.Scan(&origin.id, &origin.originKind, &origin.originID,
			&origin.deliveredAt); err != nil {
			return nil, err
		}
		origins = append(origins, origin)
	}
	return origins, rows.Err()
}

func (s *sqlStore) cleanupDeliveredGovernanceOrigin(
	ctx context.Context, tx *sql.Tx, origin deliveredGovernanceOrigin, before time.Time,
) error {
	_, err := tx.ExecContext(ctx, s.rebind(`INSERT INTO audit_governance_delivered_origins
(origin_kind,origin_id,delivered_at_ns) VALUES ($1,$2,$3)
ON CONFLICT (origin_kind,origin_id) DO NOTHING`),
		origin.originKind, origin.originID, origin.deliveredAt)
	if err != nil {
		return err
	}
	_, err = tx.ExecContext(ctx, s.rebind(`DELETE FROM audit_governance_outbox
WHERE id=$1 AND delivered_at_ns>0 AND delivered_at_ns <= $2`),
		origin.id, before.UTC().UnixNano())
	return err
}
