ALTER TABLE ai_usage ADD COLUMN model TEXT NOT NULL DEFAULT '';
ALTER TABLE ai_usage ADD COLUMN prompt_tokens INT NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN completion_tokens INT NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN total_tokens INT NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN latency_ms BIGINT NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN cost_micros BIGINT NOT NULL DEFAULT 0;
